

export const ADD_CONSTRUCTED_INGREDIENT: "ADD_CONSTRUCTED_INGREDIENT" = "ADD_CONSTRUCTED_INGREDIENT";
export const DELETE_CONSTRUCTED_INGREDIENT: "DELETE_CONSTRUCTED_INGREDIENT" = "DELETE_CONSTRUCTED_INGREDIENT";
export const MOVE_CONSTRUCTED_INGREDIENT: "MOVE_CONSTRUCTED_INGREDIENT" = "MOVE_CONSTRUCTED_INGREDIENT";
export const RESET_CONSTRUCTED_INGREDIENTS: "RESET_CONSTRUCTED_INGREDIENTS" = "RESET_CONSTRUCTED_INGREDIENTS";