export const REGISTRATION_REQUEST: "REGISTRATION_REQUEST" =
  "REGISTRATION_REQUEST";
export const REGISTRATION_FAILED: "REGISTRATION_FAILED" = "REGISTRATION_FAILED";
export const REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS" =
  "REGISTRATION_SUCCESS";
export const SIGN_IN_REQUEST: "SIGN_IN_REQUEST" = "SIGN_IN_REQUEST";
export const SIGN_IN_FAILED: "SIGN_IN_FAILED" = "SIGN_IN_FAILED";
export const SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS" = "SIGN_IN_SUCCESS";
export const SIGN_OUT_REQUEST: "SIGN_OUT_REQUEST" = "SIGN_OUT_REQUEST";
export const SIGN_OUT_FAILED: "SIGN_OUT_FAILED" = "SIGN_OUT_FAILED";
export const SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS" = "SIGN_OUT_SUCCESS";
export const GET_USER_REQUEST: "GET_USER_REQUEST" = "GET_USER_REQUEST";
export const GET_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";
export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const SET_USER_REQUEST: "SET_USER_REQUEST" = "SET_USER_REQUEST";
export const SET_USER_FAILED: "SET_USER_FAILED" = "SET_USER_FAILED";
export const SET_USER_SUCCESS: "SET_USER_SUCCESS" = "SET_USER_SUCCESS";
export const NEW_TOKEN_REQUEST: "NEW_TOKEN_REQUEST" = "NEW_TOKEN_REQUEST";
export const NEW_TOKEN_FAILED: "NEW_TOKEN_FAILED" = "NEW_TOKEN_FAILED";
export const NEW_TOKEN_SUCCESS: "NEW_TOKEN_SUCCESS" = "NEW_TOKEN_SUCCESS";
export const PASSWORD_FORGOT_REQUEST: "PASSWORD_FORGOT_REQUEST" =
  "PASSWORD_FORGOT_REQUEST";
export const PASSWORD_FORGOT_FAILED: "PASSWORD_FORGOT_FAILED" =
  "PASSWORD_FORGOT_FAILED";
export const PASSWORD_FORGOT_SUCCESS: "PASSWORD_FORGOT_SUCCESS" =
  "PASSWORD_FORGOT_SUCCESS";
export const PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST" =
  "PASSWORD_RESET_REQUEST";
export const PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED" =
  "PASSWORD_RESET_FAILED";
export const PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS" =
  "PASSWORD_RESET_SUCCESS";
export const SET_AUTHORIZED: "SET_AUTHORIZED" = "SET_AUTHORIZED";
