export const INGREDIENT_REQUEST: "INGREDIENT_REQUEST" = "INGREDIENT_REQUEST";
export const INGREDIENT_SUCCESS: "INGREDIENT_SUCCESS" = "INGREDIENT_SUCCESS";
export const INGREDIENT_FAILED: "INGREDIENT_FAILED" = "INGREDIENT_FAILED";
