export const ORDER_REQUEST: "ORDER_REQUEST" = "ORDER_REQUEST";
export const ORDER_SUCCESS: "ORDER_SUCCES" = "ORDER_SUCCES";
export const ORDER_FAILED: "ORDER_FAILED" = "ORDER_FAILED";
export const ORDER_RESET: "ORDER_RESET" = "ORDER_RESET";
